version: '3'

services:
  ryukyu-users-service:
    build: .
    image: ryukyu-users-service-img
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "7000:7000"
    links:
      - db-users
    #environment:
    #  - NODE_ENV=production
  db-users:
    image: mysql:5.7
    ports:
      - "5300:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password