version: '3'

services:
  ryukyu-users-service:
    build: ./user_management
    image: kenle545/ryukyu-users-service-img
    ports:
      - "8000:8000"
    volumes:
      - ./user_management:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-users
    environment:
      - NODE_ENV=development
  
  db-users:
    image: mysql:5.7
    ports:
      - "5300:3306"
    volumes:
      - ./user_management/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  ryukyu-user-photos-service:
    build: ./user_photos
    image: ryukyu-user-photos-service-img
    ports:
      - "8001:8001"
    volumes:
      - ./user_photos:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-user-photos
    environment:
      - NODE_ENV=development

  db-user-photos:
    image: mysql:5.7
    ports:
      - "5301:3306"
    volumes:
      - ./user_photos/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

  ryukyu-projects-service:
    build: ./projects
    image: ryukyu-projects-service-img
    ports:
      - "8002:8002"
    volumes:
      - ./projects:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-projects
      - ryukyu-users-service
    environment:
      - NODE_ENV=development

  db-projects:
    image: mysql:5.7
    ports:
      - "5302:3306"
    volumes:
      - ./projects/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  
  ryukyu-tasks-service:
    build: ./tasks
    image: ryukyu-tasks-service-img
    ports:
      - "8003:8003"
    volumes:
      - ./tasks:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-tasks
    environment:
      - NODE_ENV=development

  db-tasks:
    image: mysql:5.7
    ports:
      - "5303:3306"
    volumes:
      - ./tasks/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password