version: '3'

services:
  ryukyu-project-photos-service:
    build: .
    image: ryukyu-project-photos-service-img
    ports:
      - "8004:8004"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-project-photos
    environment:
      - NODE_ENV=development

  db-project-photos:
    image: mysql:5.7
    ports:
      - "5304:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password