version: '3'

services:
  ryukyu-tasks-service:
    build: .
    image: ryukyu-tasks-service-img
    ports:
      - "8003:8003"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-tasks
    environment:
      - NODE_ENV=development

  db-tasks:
    image: mysql:5.7
    ports:
      - "5303:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password