version: '2'

services:
  ryukyu-tasks-service:
    build: .
    image: ryukyu-tasks-service-img
    ports:
      - "5003:5003"
    volumes:
      - .:/usr/src/app
    links:
      - db-tasks
    environment:
      - NODE_ENV=development

  db-tasks:
    image: mysql:5.7
    ports:
      - "5303:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password