version: '3'

services:
  ryukyu-user-photos-service:
    build: .
    image: ryukyu-user-profile-service-img
    ports:
      - "8005:8005"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-user-profile
    environment:
      - NODE_ENV=development

  db-user-profile:
    image: mysql:5.7
    ports:
      - "5305:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password