version: '3'

services:
  ryukyu-groups-service:
    build: .
    image: ryukyu-groups-service-img
    ports:
      - "8008:8008"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - db-groups
    environment:
      - NODE_ENV=development

  db-groups:
    image: mysql:5.7
    ports:
      - "5308:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password