version: '3'

services:
  ryukyu-user-photos-service:
    build: .
    image: ryukyu-user-photos-service-img
    ports:
      - "7001:7001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db-user-photos
    environment:
      - NODE_ENV=development

  db-user-photos:
    image: mysql:5.7
    ports:
      - "5301:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password